[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'kana/vim-filetype-haskell'

[[plugins]]
repo = 'mxw/vim-jsx'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'

[[plugins]]
repo = 'vim-jp/cpp-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'JesseKPhillips/d.vim'

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'kballard/vim-fish'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'nixprime/cpsm'
build = 'sh -c "PY3=ON ./install.sh"'

[[plugins]]
repo = 'chemzqm/denite-git'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'Shirk/vim-gas'

[[plugins]]
repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'https://github.com/roxma/nvim-yarp'

[[plugins]]
repo = 'uplus/deoplete-solargraph'

