# [[plugins]]
# repo = 'zchee/deoplete-clang'
# on_ft = ['c', 'cpp']
# hook_source = '''
# " libclang shared library path
# let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
# " For Ubuntu
# " let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.8/lib/libclang-3.8.so'
#
# " clang builtin header path
# let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
#
# " libclang default compile flags
# let g:deoplete#sources#clang#flags = ['-x', 'c++', '-std=c++11']
#
# " compile_commands.json directory path
# " Not file path. Need build directory path
# " let g:deoplete#sources#clang#clang_complete_database =
# "       \ expand('~/src/neovim/build')
# '''

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
on_ft = ['c', 'cpp']
hook_source = '''
  autocmd FileType c,cpp let b:clang2_orig_maps = {}
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = 'zsh'

[[plugins]]
repo = 'zchee/deoplete-go'
on_i = 1
on_ft = 'go'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
source ~/.vim/rc/plugins/deoplete.rc.vim
'''

