[[plugins]]
repo = 'Shougo/dpp.vim'
description = 'Dark powered plugin manager for Vim/Neovim'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
rtp = ''

[[plugins]]
repo = 'Shougo/dpp-ext-toml'
hook_add = '''
" Enable dpp toml syntax.
if !has('nvim')
  autocmd MyAutoCmd CursorHold */rc/*.toml call dpp#ext#toml#syntax()
endif
'''

[[plugins]]
repo = 'Shougo/dpp-ext-local'

[[plugins]]
repo = 'Shougo/dpp-ext-installer'

[[plugins]]
repo = 'Shougo/dpp-ext-packspec'

[[plugins]]
repo = 'Shougo/dpp-protocol-git'

[[plugins]]
repo = 'Shougo/dpp-protocol-http'
